[GAP_lib]
git-tree-sha1 = "6faff9ec58fcefa44d6bacb618a0044d549d091e"

    [[GAP_lib.download]]
    sha256 = "792ddbbaa864da1fe52da1ed184b49913d74a14da82f204b0802fe3da68fd14b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_lib_jll.jl/releases/download/GAP_lib-v4.11.0+1/GAP_lib.v4.11.0.any.tar.gz"
